<?php

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Removes all generated image derivatives (resized, cropped, thumbnails, …)
 * from the cache directory configured under image.cache_dir.
 *
 * Usage:
 *   php bin/console image:clear-cache
 *   php bin/console image:clear-cache --dry-run
 */
#[AsCommand(
    name: 'image:clear-cache',
    description: 'Removes cached image derivatives generated by ImageService',
)]
class ImageClearCacheCommand extends Command
{
    public function __construct(private readonly string $cacheDir)
    {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Only report what would be removed')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $dryRun = (bool) $input->getOption('dry-run');

        if (!is_dir($this->cacheDir)) {
            $output->writeln(sprintf('<info>No image cache to clear (<info>%s</info> does not exist).</info>', $this->cacheDir));

            return Command::SUCCESS;
        }

        $files = $this->collectFiles($this->cacheDir);
        $count = 0;
        $freed = 0;

        foreach ($files as $file) {
            if (!is_file($file)) {
                continue;
            }

            $freed += filesize($file) ?: 0;
            $count++;

            if (!$dryRun) {
                @unlink($file);
            }
        }

        if ($dryRun) {
            $output->writeln(sprintf('<comment>Dry-run: %d cached image(s) would be removed (%s).</comment>', $count, $this->formatBytes($freed)));

            return Command::SUCCESS;
        }

        $this->removeEmptyDirectories($this->cacheDir);

        $output->writeln(sprintf('<info>Cleared %d cached image derivative(s) (%s).</info>', $count, $this->formatBytes($freed)));

        return Command::SUCCESS;
    }

    /**
     * @return list<string>
     */
    private function collectFiles(string $dir): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($dir, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::LEAVES_ONLY
        );

        foreach ($iterator as $file) {
            if ($file->isFile()) {
                $files[] = $file->getRealPath();
            }
        }

        return $files;
    }

    private function removeEmptyDirectories(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        foreach (glob($dir.'/*') ?: [] as $child) {
            if (is_dir($child)) {
                $this->removeEmptyDirectories($child);
            }
        }

        if (is_dir($dir)) {
            @rmdir($dir);
        }
    }

    private function formatBytes(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB'];

        foreach ($units as $unit) {
            if ($bytes < 1024) {
                return round($bytes, 2).' '.$unit;
            }
            $bytes /= 1024;
        }

        return round($bytes, 2).' TB';
    }
}

